steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/${_APP_NAME}-${_APP_SERVICE}:${_APP_VERSION}', '.' ]

images: [
  'gcr.io/$PROJECT_ID/${_APP_NAME}-${_APP_SERVICE}:${_APP_VERSION}'
]